### ISSUE TITLE
encoding problems when saving/loading requests

### ISSUE THREAD

**Issue by dkounal** [DelphiWorlds/Slumber#12]
If using characters outside the latin alphabet for naming requests, or to body content to send in a request, saving to json all requests and reloading again causes these characters to be garbage.

**Comment by DelphiWorlds** [comment]
Can you provide an example of the text it has problems with?

**Comment by dkounal** [comment]
![εικόνα](https://github.com/DelphiWorlds/Slumber/assets/37013295/96f15f41-5af2-46d4-bae0-3a2ee3d2a104)
The above is the original-correct presentation
The following is the image after reloading the json file:
![εικόνα](https://github.com/DelphiWorlds/Slumber/assets/37013295/0ef68a13-9cc1-49cc-8b05-db41d1c8376b)
And the saved json is:
[testGreekChars.zip](https://github.com/DelphiWorlds/Slumber/files/12138810/testGreekChars.zip)
The JSON should be UTF-8 by default. I think that Delphi needs always a conversion when a utf8string is assigned to string

**Comment by DelphiWorlds** [comment]
Thanks.. pushed a change to SL.Storage.Profile.pas that should fix this.

**Comment by dkounal** [comment]
Thank you. waiting for it.

**Comment by DelphiWorlds** [comment]
Sorry, my git client got "stuck"..
